services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm start
